### PR TITLE
creates dir structure and cleans build dir

### PR DESCRIPTION
**Pull request by scriptnull**
https://github.com/Shippable/reqProc/issues/39
https://github.com/Shippable/reqProc/issues/40

When everything passes
image

Following failures are caused by setting `err` object to true explicitly ( for taking these screenshots )

When creating a dir fails
image

When creating a file fails
image

When cleanup fails
image

### CODE REVIEW

**Comment by ric03uec** [comment]
are the logs for these pushed out to build job console?

**Comment by scriptnull** [comment]
An example of how the current console looks like when reqProc is being run is 

image

Should we be sending console logs with new groups like "Setting up Directories" , "Build cleanup" etc. in this step ?

**Comment by ric03uec** [comment]
we need logs for this section in the console. it should say "Creating job directories" at the group level and should list the directories being created in that group

**Comment by ric03uec** [comment]
also, like you mentioned, it should have the cleanup group with correct logs

**Pull request merged**
