### PR TITLE
Enhance Windows dockerfile

### PR DESCRIPTION
**Pull request by rageshkrishna**
https://github.com/Shippable/reqProc/issues/217

### CODE REVIEW

**Comment by ambarish2012** [comment]
@rageshkrishna we should not use C:/Users directly but environment variables. We cannot assume windows is always installed in the C drive.

**Comment by rageshkrishna** [comment]
This is running inside the windowsservercore container, not on the host. Is it still a problem?

**Comment by rageshkrishna** [comment]
@ambarish2012 I investigated this, and there are issues with not being able to do this correctly while using the `ENV` directive, and it would not work anyway with `WORKDIR`. I think it's highly unlikely that `C:\Users\ContainerAdministrator` is going to change in a pinned servercore image, so I think we should punt this for now and get back to it when we have more time.

**Comment by rageshkrishna** [comment]
Discussed this with @ambarish2012 offline. Merging.

**Pull request merged**
